### ISSUE TITLE
Default command for intake subsystem

### ISSUE THREAD

**Issue by mpulte** [Robocubs/2024RobotCode#19]
The default command for the intake should

- Take a `BooleanSupplier` `canPassNote` for if the note can be passed to the indexer. This should be true if elevator is down.
- Take a `BooleanSupplier` `canIntakeNote` for if new piece can be intaked. This should be false if we have a note anywhere in the robot.
- Stop if `canIntakeNote` is false and intake does not have the piece
- Stop if `canPassNote` and intake has a piece
- Otherwise, run forward. Use low speed if the intake doesn't have a piece. Use high speed if the intake has a piece.

**Comment by tenumars** [comment]
Closed with PR #39
